# ----------------------------------------
# Common Configuration (Applied Everywhere)
# ----------------------------------------

# App Name
spring.application.name=Parcel Management System

# Default profile (set to dev for local, override in prod)
spring.profiles.active=dev

# Hibernate common settings
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Multipart file size limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Logging
logging.level.org.springframework=INFO
logging.level.com.pms=DEBUG



#spring.application.name=parcel management system
#
##------------------ Start Production k liye code ----------
#
## Port: Render set kare to use karo, warna 8080
#server.port=${PORT:8080}
#
## Static cache (optional, better performance)
#spring.web.resources.cache.period=365d
#spring.web.resources.chain.enabled=true
#
##------------------ End Production-------------------------
#
## Database
#spring.datasource.url=jdbc:mysql://localhost:3306/parcel_db
#spring.datasource.username=root
#spring.datasource.password=root
#
## JPA
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
## File upload settings
#file.upload-dir=uploads
#spring.servlet.multipart.enabled=true
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=10MB
#
## Debug
#logging.level.org.springframework.transaction=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#
## application.properties
##spring.jackson.format.date-time=yyyy-MM-dd'T'HH:mm:ss
##spring.jackson.time-zone=UTC
## Enable Hibernate's ISO8601 format for Instant
#spring.jackson.serialization.write-dates-as-timestamps=false
#spring.jackson.time-zone=UTC
#spring.jackson.deserialization.adjust-dates-to-context-time-zone=false
#
## JWT
#app.jwtSecret=yourSecretKeyForJWTSigning12345
#app.jwtExpirationMs=86400000 # 24 hours
